#!/usr/bin/env python
import time
import argparse

import semidbm


def measure_laod_time(db_path):
    num_loads = 10
    times = []
    o = semidbm.open
    for  i in range(num_loads):
        start = time.time()
        db = o(db_path, 'c')
        times.append(time.time() - start)
        db.close()
    print "%.5f milliseconds average load time" % (
        (sum(times) / float(num_loads)) * 1000)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('db_path')
    args = parser.parse_args()
    measure_laod_time(args.db_path)


if __name__ == '__main__':
    main()
